export const ENCOUNTER_EVENTS = {
    ENCOUNTER_CREATED: 'ENCOUNTER_CREATED',
    ENCOUNTER_COMPLETED: 'ENCOUNTER_COMPLETED',
    ENCOUNTER_REMOVED: 'ENCOUNTER_REMOVED',
    ENCOUNTER_UPDATED: 'ENCOUNTER_UPDATED'
    };
    
