import { EVENT_TYPES } from '../../shared/events/eventTypes.js';

export const ENCOUNTER_EVENTS = {
    ENCOUNTER_CREATED: `${EVENT_TYPES.ENCOUNTER}.CREATED`,
    ENCOUNTER_COMPLETED: `${EVENT_TYPES.ENCOUNTER}.COMPLETED`,
    ENCOUNTER_REMOVED: `${EVENT_TYPES.ENCOUNTER}.REMOVED`,
    ENCOUNTER_UPDATED: `${EVENT_TYPES.ENCOUNTER}.UPDATED`,
};
