import { EVENT_TYPES } from "../../shared/events/eventTypes.js";

export const QUEST_EVENTS = {
    QUEST_CREATED: `${EVENT_TYPES.QUEST}.CREATED`,
    QUEST_COMPLETED: `${EVENT_TYPES.QUEST}.COMPLETED`,
    QUEST_DEADLINE_UPDATED: `${EVENT_TYPES.QUEST}.DEADLINE_UPDATED`,
    QUEST_CANCELLED: `${EVENT_TYPES.QUEST}.CANCELLED`
};

