import { EVENT_TYPES } from '../../shared/events/eventTypes.js';

export const CHARACTER_EVENTS = {
    CHARACTER_CREATED: `${EVENT_TYPES.CHARACTER}.CREATED`,
    GAINED_EXPERIENCE: `${EVENT_TYPES.CHARACTER}.GAINED_EXPERIENCE`,
    GAINED_GOLD: `${EVENT_TYPES.CHARACTER}.GAINED_GOLD`,
    SPENT_GOLD: `${EVENT_TYPES.CHARACTER}.SPENT_GOLD`,
    ACQUIRED_LOOT: `${EVENT_TYPES.CHARACTER}.ACQUIRED_LOOT`,
    REMOVED_LOOT: `${EVENT_TYPES.CHARACTER}.REMOVED_LOOT`,
    LEVEL_CHANGED: `${EVENT_TYPES.CHARACTER}.LEVEL_CHANGED`,
  };

  export const LOOT_TYPES = {
    ITEM: 'ITEM',
    GOLD: 'GOLD'
  };