export const CHARACTER_EVENTS = {
    CHARACTER_CREATED: 'CHARACTER_CREATED',
    GAINED_EXPERIENCE: 'GAINED_EXPERIENCE',
    GAINED_GOLD: 'GAINED_GOLD',
    SPENT_GOLD: 'SPENT_GOLD',
    ACQUIRED_LOOT: 'ACQUIRED_LOOT',
    REMOVED_LOOT: 'REMOVED_LOOT',
    LEVEL_CHANGED: 'LEVEL_CHANGED'
  };

  export const LOOT_TYPES = {
    ITEM: 'ITEM',
    GOLD: 'GOLD'
  };
  