const CHARACTER_EVENTS = {
    CHARACTER_CREATED: 'CHARACTER_CREATED',
    GAINED_EXPERIENCE: 'GAINED_EXPERIENCE',
    GAINED_GOLD: 'GAINED_GOLD',
    SPENT_GOLD: 'SPENT_GOLD',
    ACQUIRED_LOOT: 'ACQUIRED_LOOT',
    LEVEL_CHANGED: 'LEVEL_CHANGED'
  };
  
  module.exports = { CHARACTER_EVENTS };